### ISSUE TITLE
Multiple acts_as_notifiable, same underlying model, different target_type

### ISSUE THREAD

**Issue by apuntovanini** [simukappu/activity_notification#142]
In our use case we'd need to set an acts_as_notifiable on two different target_types of the same model. Someone donates to an organization, and we need to trigger a donation.create notification to organization admins as well as donor. In our case though, organization admins and donors are all Contact.

```ruby
acts_as_notifiable :contacts,
                     targets: lambda { |donation, _key|
                       donation.organization.members
                     },
                     optional_targets: {
                       NotificationTargets::WebPush => {}
                     },
                     notifier: :contact,
                     group: :donation_campaign,
                     notifiable_path: :admin_url,
                     parameters: lambda { |donation, _key|
                                   {
                                     notifier_name: donation.contact.full_name,
                                     donation_amount: donation.amount / 100,
                                     donation_campaign_name: donation.donation_campaign.name
                                   }
                                 }
  acts_as_notifiable :donors,
                     targets: lambda { |donation, _key|
                       [donation.contact]
                     },
                     notifier: :organization,
                     notifiable_path: :public_url,
                     parameters: lambda { |donation, _key|
                                   {
                                     notifier_name: donation.organization.name,
                                     donation_amount: donation.amount / 100,
                                     donation_campaign_name: donation.donation_campaign.name
                                   }
                                 }
```

The way I implemented doesn't work because the insist on the same model (contact). Why isnt' target_type just a name helper? Targets are defined anyways, isn't it?
Thanks for your support, best gem ever found for notifications

**Comment by apuntovanini** [comment]
I guess it's pretty similar to https://github.com/simukappu/activity_notification/issues/74#issuecomment-399898359

**Comment by simukappu** [comment]
Thank you for your question and proposal.
Currently, target_type is not just a name helper but saved with model class name as key. If *acts_as_notifiable* saves target model class in notifiable model, like `Contact` model in your example, we may become able to use target_type as a name helper.

It will be a big change for this gem. We would appreciate your contribution.

**Comment by apuntovanini** [comment]
Thanks @simukappu, I can work on a PR next week. In the meantime, please check #139 and the other pending PR

**Comment by simukappu** [comment]
We've just published as v2.1.4 including support for STI models by #89 and #139.
https://rubygems.org/gems/activity_notification/versions/2.1.4

Closing this issue for now. Please reopen if required.

**Comment by apuntovanini** [comment]
Hello @simukappu sorry to come back on this, but while #89 and #139 correctly addressed STI, I think the original issue is still relevant. I came back to this by accident, and figure out that the example I posted works only because by calling the first acts_as_notifiable with a name that corresponds to a model (:contacts), something (unclear to me) is registered to the model, and allow use :donors as another acts_as_notifiable key. If i invert those methods, everything breaks.

This comment https://github.com/simukappu/activity_notification/issues/74#issuecomment-399901861 gives a clue on how to use multiple acts_as_notifiable within the same model, but I think it makes the command less clear.
Can you please explain the logic of saving the target key into the model? I can work on a proposal on how to change this if it's a good direction for you, but I need to understand its logic a little bit more!
Thanks!
