### ISSUE TITLE
Allow use with Rails 6.1

### ISSUE THREAD

**Issue by simukappu** [simukappu/activity_notification#152]
Rails 6.1 has been released.
https://edgeguides.rubyonrails.org/6_1_release_notes.html

*activity_notification* also should support Rails 6.1.

**Comment by simukappu** [comment]
Waiting for [devise_token_auth](https://rubygems.org/gems/devise_token_auth) support with Rails 6.1 in order to make existing tests.

**Comment by simukappu** [comment]
Also waiting for [mongoid](https://github.com/mongodb/mongoid) support with Rails 6.1.

**Comment by sjieg** [comment]
Hey @simukappu looks like the mongoid ticket has been solved. Mind having another look at it? :)

**Comment by simukappu** [comment]
Hi @sjieg,
Thank you for letting me know, but the mongoid ticket has not been released in [the latest v7.2.0](https://rubygems.org/gems/mongoid/versions/7.2.0). Still looking at mongoid and devise_token_auth update.

**Comment by sjieg** [comment]
I see, fair enough.

I'm a little bit surprised with these dependencies. As we're using this gem with MySQL and I don't think we use any of the MongoDB dependencies.
I think the same thing counts for the `devise_token_auth` dependency.

I mean, you're doing a great job maintaining this Gem, really good stuff. Just some food for thought. I wouldn't have a clue what the standards are on having (semi-)optional dependencies.

**Comment by apuntovanini** [comment]
I also think that the gem should have less opinionated dependencies, devise_token_auth is needed for the demo I think, not for the gem to work

**Comment by simukappu** [comment]
Thank you for your feedback. I got it.
I will try to allow use with Rails 6.1 except for mongoid ORM. API tests are using device_token_auth, so will use master branch as dev dependency.

**Comment by apuntovanini** [comment]
Do you need any help with this @simukappu?

**Comment by simukappu** [comment]
Thank you @apuntovanini. Can you test this gem from development branch with your app?

**Comment by apuntovanini** [comment]
It works! @simukappu 
Only issue is
```bash
DEPRECATION WARNING: Initialization autoloaded the constants MailerHelper and ActivityNotification::Mailer.

Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.
```

I already wrapper initializer in Rails.application.reloader.to_prepare do end

**Comment by simukappu** [comment]
I've published [v2.2.1](https://rubygems.org/gems/activity_notification/versions/2.2.1) working with Rails 6.1.
Note that latest mongoid release does not allow use with Rails 6.1 and this gem is making test with master branch. Also Dynamoid is not tested with Rails 6.1.
Thanks!

**Comment by apuntovanini** [comment]
@simukappu just to understand whether the warning comes from the gem or from our side, we're still seeing the 
```ruby
DEPRECATION WARNING: Initialization autoloaded the constants MailerHelper and ActivityNotification::Mailer.

Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.
```
Does it happen to you as well?
This is our initializer
```ruby
Rails.application.reloader.to_prepare do
  # ...

  # Configure the class responsible to send e-mails.
  config.mailer = 'ActivityNotification::Mailer'

  # Configure the parent class responsible to send e-mails.
  config.parent_mailer = 'ApplicationMailer'

  # Configure the parent job class for delayed notifications.
  config.parent_job = 'ApplicationJob'
  
  # ...
end
